### ISSUE TITLE
Incorrect clearing of interrupt flag PCIF2 in setup()

### ISSUE THREAD

**Issue by PBudmark** [JChristensen/PowerOutageMonitor_SW#1]
Hi,
In the setup function, at line 165 there is an attempt to clear PCIF2 in register PCIFR, but actually that is not what happens.
Clearing a interrupt flag (as PCIF2) should be done writing a one to the flag bit (and writing zeroes to all other bits).
The actual code resets any other flag in the register but PCIF2.
Correct code is:
`PCIFR = _BV(PCIF2); //ensure interrupt flag is cleared`

**Comment by JChristensen** [comment]
Sure enough. Thanks for the catch!
